## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

# 1: make the vectors

In [1]:
import numpy as np

In [36]:
a = np.arange(5,10)
b = np.arange(15,20)

a, b

(array([5, 6, 7, 8, 9]), array([15, 16, 17, 18, 19]))

# non-numpy: outerprod and trace

In [40]:
# outer product

def findOuterProd_dc(vec1, vec2):
    outerProd = [] # initialize empty list
    # check to make sure lists are same length
    if (len(vec1)!=len(vec2)):
        out='lists must be same length'
    else:
        for i in range(len(vec1)): #iterate through vec1
            row = [] #empty list to be populated
            for j in range(len(vec2)): #iterate through vec2
                row.append(vec1[i]*vec2[j]) #populate row which is each member of vec2*i'th element of vec1
            outerProd.append(row) #append each multiplied row to the big vector outerProd..
        out = outerProd
    return out

findOuterProd_dc(a, b)

[[75, 80, 85, 90, 95],
 [90, 96, 102, 108, 114],
 [105, 112, 119, 126, 133],
 [120, 128, 136, 144, 152],
 [135, 144, 153, 162, 171]]

In [41]:
# compute "trace"
def findTrace_dc(vec):
    dimension = len(vec)
    diagonalSum=0 #initialize diagonal sum
    for i in range(0,dimension):
        diagonalSum += vec[i][i]
    return diagonalSum
findTrace_dc(outerProd)

605

# numpy: outerprod and trace

In [42]:
# outer product using numpy
outerProdNP = np.outer(a,b)
outerProdNP

array([[ 75,  80,  85,  90,  95],
       [ 90,  96, 102, 108, 114],
       [105, 112, 119, 126, 133],
       [120, 128, 136, 144, 152],
       [135, 144, 153, 162, 171]])

In [49]:
# compute "trace" using numpy
def findTraceNumpy_dc(vec):
    rowCount = vec.shape[0]
    colCount = vec.shape[1]
    if rowCount==colCount:
        diagonalSum=0 #initialize diagonal sum
        for i in range(0,rowCount):
            diagonalSum += vec[i][i]
    else:
        out = 'need square matrix!'
    out=diagonalSum
    return out

findTraceNumpy_dc(outerProdNP)

605

### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the resulting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [60]:
# generate a matrix(rows,cols) of uniformly distributed random numbers over 0:20
A = np.round(np.random.rand(4,3)*20)   
B = np.round(np.random.rand(3,4)*20)

print("A:\n", A, "\nB:\n",B)

A:
 [[18. 19.  4.]
 [ 9. 14.  3.]
 [ 7.  3. 14.]
 [ 1. 18. 18.]] 
B:
 [[ 8. 12. 14. 14.]
 [15. 13.  3. 11.]
 [ 9.  0. 20. 14.]]


# AB: for-loop

# AB: list comprehension

# AB: numpy